### ISSUE TITLE
Completely silent notifications even without vibrations

### ISSUE THREAD

**Issue by vholer** [NetworksAreMadeOfString/Rhybudd#13]
Even if I disable notification sound, each notification update results in device vibration (Nexus S, Android 4.1.2). Which can be very often if you working in UI and refreshing events often.

**Comment by NetworksAreMadeOfString** [comment]
Will fix this in 4.0

**Comment by NetworksAreMadeOfString** [comment]
4.0 has been released so should have resolved this.
