### ISSUE TITLE
Rhybudd 3.3 with Zenoss Core 4.2.4 - Initialising the API failed?!

### ISSUE THREAD

**Issue by defkev** [NetworksAreMadeOfString/Rhybudd#14]
That's what i get on initial Setup/Login of Rhybudd along with "An error has been logged" or something like that (Sorry but the message is just vanishing way to fast)

Afterwards i can see my infrastructure for a short time until every connection to Zenoss from within Rhybudd just fails/times out with errors like:

"DB Cache incomplete. Querying Zenoss directly. Please wait..."
"An error was encountered. Please check your settings and try again."
"Querying Zenoss Directly - Refreshing Events..."
"An error was encountered. Please check your settings and try again."
...

and so on until i reboot the phone.

It then works again for a few minutes until the connection problems start all over again.

I already checked the Zenoss logs on my Hub but couldn't find anything.

As a side note, i am testing this on a fairly small Installation in our Lab with only 16 monitored Devices.

Thanks in advanced!
Cheers

**Comment by NetworksAreMadeOfString** [comment]
Hi DefKev,

That does sound quite strange, would you be interested in Alpha testing 4.0?

Join this G+ group: https://plus.google.com/communities/104451514491198459171

Then navigate to here: https://play.google.com/apps/testing/net.networksaremadeofstring.rhybudd

It'll invite you to get access to the Alpha and then you'll be able to access it from Google Play as if it was a normal release.

Gareth

**Comment by NetworksAreMadeOfString** [comment]
Hi DefKev,

4.0 has been released and should resolve your issues. If you are still having issues then the Diagnostics feature should help; http://wiki.zenoss.org/Android#Diagnostics

Gareth
