### ISSUE TITLE
Allow longer poll interval

### ISSUE THREAD

**Issue by TravellingGuy** [NetworksAreMadeOfString/Rhybudd#2]
Allow a longer poll interval to be defined.  I'd like to be able to specify a poll interval of 15 minutes.

**Comment by NetworksAreMadeOfString** [comment]
Done, published to market as version 1.6.

Thank you for using GitHub issue tracker rather than Market review.

**Comment by TravellingGuy** [comment]
Thanks!

**Comment by NetworksAreMadeOfString** [comment]
There may be an issue with this release, whilst it works fine on the emulator, on my Sensation it seems to stop raising alerts after a while even though the service is still running. 

Will investigate and get a fix out if necessary.

**Comment by NetworksAreMadeOfString** [comment]
Found the problem - will need a rewrite of the poller backend. Will try and get it done ASAP.

**Comment by NetworksAreMadeOfString** [comment]
Resolved the issue but I'm testing on a variety of devices (G2, Sensation, WildFire & the emulator) for a little while to make sure it is actually fixed.

**Comment by NetworksAreMadeOfString** [comment]
Fixed. 

1.7 released to market with additional features.
