### ISSUE TITLE
Only alert for servers in Production

### ISSUE THREAD

**Issue by TravellingGuy** [NetworksAreMadeOfString/Rhybudd#4]
Nice work so far!  Very much liking (gave you 5 stars on the Android market).

I'm only concerned about servers that I have in a production state (Production State = "Production") in the devices list and don't want to be notified if a test server fails in the middle of the night.

It would be handy to allow the user to specify what production states Rhybudd should alert on.

**Comment by NetworksAreMadeOfString** [comment]
Cool, will add that to the filter ability. 

Initial release is likely to be a global filter - I'll make it more fine grained later on.

**Comment by NetworksAreMadeOfString** [comment]
Production only alerting option is done.

Will be in the 2.0 release
