### ISSUE TITLE
Is pagerduty required?

### ISSUE THREAD

**Issue by johnfisher** [NetworksAreMadeOfString/Rhybudd#6]
I can't seem to get past that field when I install.

**Comment by NetworksAreMadeOfString** [comment]
Hi John,

Apologies for the delay, I've been on annual leave.

It is not and will be moved to it's own section later on.

If you can't get past the settings then it means that Rhybudd is receiving back a 401 or other non 200 HTTP code / erroneous JSON from the request it does to ensure that the credentials are correct.

Are you specifying the port etc in the URL and including the schema such as http:// or https:// ?

**Comment by johnfisher** [comment]
thanks, no apology needed. I see what stopped me before. Just pilot error.

On 12/09/2011 03:20 AM, Gareth Llewellyn wrote:

> Hi John,
> 
> Apologies for the delay, I've been on annual leave.
> 
> It is not and will be moved to it's own section later on.
> 
> If you can't get past the settings then it means that Rhybudd is receiving back a 401 or other non 200 HTTP code / erroneous JSON from the request it does to ensure that the credentials are correct.
> 
> Are you specifying the port etc in the URL and including the schema such as http:// or https:// ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/NetworksAreMadeOfString/Rhybudd/issues/6#issuecomment-3077856

## 

John Fisher

**Comment by NetworksAreMadeOfString** [comment]
Cool.
