### ISSUE TITLE
Device Details: "An error was encountered parsing the JSON"

### ISSUE THREAD

**Issue by whytee** [NetworksAreMadeOfString/Rhybudd#7]
I get a toaster notification with the above error whenever I try to view a device's details. The list of devices populates fine.

Running Zenoss 3.2.0, device is a Galaxy S II on a 2.3.3 ROM. Happy to produce more info or logs (if you tell me where to look :o).

**Comment by NetworksAreMadeOfString** [comment]
Hi, unfortunately there are quite a few possibilities that could be causing this.

I'll be adding the ability to enable BugSense ( http://www.bugsense.com/ ) error reporting in the next version which will help me to track down what is going on.

I'll keep you in the loop.

**Comment by NetworksAreMadeOfString** [comment]
This should be fixed now. If not I'll get a full exception trace via BugSense and will fix it for good!
