### ISSUE TITLE
Allow user specified notification sound

### ISSUE THREAD

**Issue by TravellingGuy** [NetworksAreMadeOfString/Rhybudd#9]
Allow the user to pick their own notification sound (preferably, a different notification sound for each of the different severity levels).

So, I can set it up so that "Critical" events play the "Ta-da", but a "Warning" event plays "Tinkerbell".

My Android default notification isn't very in-your-face, but I'd like to be able to set Critical events to play a longer, louder sound that will wake me up when I'm sleeping.  :-)

**Comment by NetworksAreMadeOfString** [comment]
This has been done and available in the 3.0 release (including the ability to set 'persistent notification' which continues to play the sound till you swipe the notification bar.)
